// Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_RECEIVED = 'FETCH_CATEGORIES_RECEIVED'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

// Posts
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS'
export const FETCH_ALL_POSTS_RECEIVED = 'FETCH_ALL_POSTS_RECEIVED'
export const FETCH_ALL_POSTS_ERROR = 'FETCH_ALL_POSTS_ERROR'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_RECEIVED = 'FETCH_POSTS_RECEIVED'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const FETCH_POST = 'FETCH_POST'
export const FETCH_POST_RECEIVED = 'FETCH_POST_RECEIVED'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'

export const ADD_POST = 'ADD_POST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'

export const SCORE_POST = 'SCORE_POST'
export const SCORE_POST_SUCCESS = 'SCORE_POST_SUCCESS'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'

// Comments
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENTS_RECEIVED = 'FETCH_COMMENTS_RECEIVED'
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'

export const EDIT_COMMENT = 'EDIT_COMMENT'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'

export const SCORE_COMMENT = 'SCORE_COMMENT'
export const SCORE_COMMENT_SUCCESS = 'SCORE_COMMENT_SUCCESS'